[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ethanNguyenUser/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
# (Optional) Text in landing page button
LANDING_BUTTON = "Open"
# (Optional) Site description on landing page
LANDING_DESCRIPTION = "These are my public Obsidian notes. Feel free to explore the graph view at the bottom of each page!"
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "Knowledge"
# (Optional) Site title on landing page
LANDING_TITLE = "Hi!"
PYTHON_VERSION = "3.8"
# (REQUIRED) Site repo URL
REPO_URL = "https://github.com/ethanNguyenUser/Knowledge"
# (Optional) Site title in navbar
SITE_TITLE = "Ethan's Notes"
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
SITE_TITLE_TAB = "Obsidian Notes"
# (REQUIRED) Netlify site URL
SITE_URL = "https://ethann.netlify.app/"
# (Optional) Site Timezone
TIMEZONE = "America/Los_Angeles"
ZOLA_VERSION = "0.15.2"
# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
SORT_BY = "title"
# (Optional) Google Analytics Measurement ID
GANALYTICS = ""
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = "y"
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = "y"
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = "y"
# (Optional, default false) Whether sidebar sections should be collapsed by default.
SIDEBAR_COLLAPSED = ""
# (Optional, default blank) Additional footer content.
FOOTER = "Made by Ethan Nguyen (2023) "
# (Optional, default main) Root section name.
ROOT_SECTION_NAME = "main"
# (Optional) visjs graph options. Can remove if desired.
GRAPH_OPTIONS = """
        {
        	nodes: {
        		shape: "dot",
        		color: isDark() ? "#8c8e91" : "#dee2e6",
        		font: {
        			face: "Inter",
        			color: isDark() ? "#c9cdd1" : "#616469",
        			strokeColor: isDark() ? "#c9cdd1" : "#616469",
        		},
        		scaling: {
        			label: {
        				enabled: true,
        			},
        		},
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 1.2,
        		smooth: {
        			type: "continuous",
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	"physics": {
    			"barnesHut": {
      				"gravitationalConstant": -22064,
    				"centralGravity": 0.1,
    				"springConstant": 0.23,
					"springLength": 300
    				"avoidOverlap": 0.3
    			},
				"maxVelocity": 50
			}
        }
        """